Event section-wip
vue-js-israel/vue-israel-website-v2 pull request #1
Opened 2023-05-23 19:26 UTC by AlexNechayev

init of event section (work in progress)

2023-05-23 19:35 UTC, dimshik100 commented on pages/events/[...slug].vue
> +// destrucure `prev` and `next` value from data
Please pay attention to correct grammar.
``` destrucure -> destructure ```

2023-05-31 19:25 UTC, dimshik100 requested changes

2023-05-31 19:25 UTC, dimshik100 commented on components/Tags.vue
> +  @apply !py-0.5 transition-all hover:-translate-y-0.5;
Check if this effect can be achieved without using `!important`.
This effect is causing the top of the tag to disappear - goes outside of the bounding box.

2023-05-31 19:25 UTC, dimshik100 commented on pages/events/index.vue
> +}
Consider moving all of this functionality to an external file, as this is a helper stuff that we might want to use in multiple pages.

Please fix the `%2C` the should be a regular `,` in the URL.
Check if this helps -> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURI

2023-05-31 19:25 UTC, dimshik100 commented on assets/css/main.css
> +.cta {
Please change this class name to something more specific.
Consider moving it to a more relevant location - as tags are only relevant in the main events page and not on all the website.

2023-05-31 19:25 UTC, dimshik100 commented on assets/css/main.css
> +.page-heading{
Looks like this should also be inside event page

2023-05-31 19:25 UTC, dimshik100 commented on components/SiteHeader.vue
> +            <img class="w-8 mr-2" src="/logo/logo.svg" alt="Vue.js Israel Community Logo"> Vue.js Israel Community
Please rename `logo.svg` to `Vue.js Israel community - logo.svg`

2023-05-31 19:25 UTC, dimshik100 commented on components/Tags.vue
> +  /* @apply transition-all max-w-0 max-h-10 overflow-hidden flex flex-row justify-center content-center; */
Please delete if not in use.

2023-05-31 19:25 UTC, dimshik100 commented on components/events/EventCard.vue
> +  };
Please remove if not in use.

2023-05-31 19:25 UTC, dimshik100 commented on content/events/data-management-with-vue.md
> +tags: [Web, Development, Frameworks, Frontend, JavaScript, Vue.js]
Please change this to `event-tags` as `tags` is a reserved key (apparently).
And fix(remove) the unneeded functionality related to `:static-tags`.

2023-05-31 19:25 UTC, dimshik100 commented on nuxt.config.ts
> +    }
This is not in use yet.
Please remove it for now.
We will add the necessary theme stuff when we get to light/dark modes.

2023-05-31 19:25 UTC, dimshik100 commented on public/images/img1.png
Please update all header images to be in a convention name that looks similar to this `Vue.js Israel meetup - Semperis - 02.05.23.png`
Also, make sure that those images have the relevant ALT where they are used.

2023-05-31 19:25 UTC, dimshik100 commented on pages/events/index.vue
> +  title: "All Events",
Please change to `Vue.js Israel Events`

2023-05-31 19:25 UTC, dimshik100 commented on pages/events/[...slug].vue
> +const [prev, next] = data.value.surround;
Please remove all `surround` related code as we are not going to use it.

2023-05-31 19:25 UTC, dimshik100 commented on pages/events/[...slug].vue
> +    },
Please remove this section, as we will address all SEO later.

2023-06-03 18:30 UTC, AlexNechayev commented
@dimshik100 Hey,
I did all the requested changes.

2023-06-04 17:37 UTC, dimshik100 approved these changes

2023-06-04 17:38 UTC, merged